### PR TITLE
Extract templates to selmer files

### PR DESCRIPTION
**Pull request by mknoszlig**
Gives the user control over the post  and index content templates.

### CODE REVIEW

**Comment by jmglov** [comment]
I've done something similar in #6. I recommend going with my PR and declining this one if it's OK with you, @mknoszlig.

**Comment by mknoszlig** [comment]
personally, i'd prefer to let the index page content be controlled via it's own template tbh. Other than that you're correct, the differences aren't all that significant. however, #6 depends on #4 which apparently still has open questions afaict?

**Comment by mknoszlig** [comment]
in order to avoid duplications like that in the future i suggest we switch to filing an issue before working on a PR right away.

**Comment by borkdude** [comment]
> in order to avoid duplications like that in the future i suggest we switch to filing an issue before working on a PR right away.

Agreed, this is how I normally work but still have to set up a PR template...

**Comment by borkdude** [comment]
@mknoszlig @jmglov :

I discussed the stuff in @jmglov's PR on Slack so we'll merge that first, after @jmglov solves the conflicts his PR. I'll make a quickblog channel so we can discuss things more in the open.

I added a PR template now.

From now on:

- Every PR must preceded with an issue with a clear problem statement, to prevent duplicate effort and to keep a PR focused to one problem
- Every PR must update the CHANGELOG.md so people upgrading know what to expect

@mknoszlig If you have any improvements after @jmglov's PR is merged, then let's follow this new way of working.

**Comment by borkdude** [comment]
Superseded by #6

**Pull request closed without merging**
