### PR TITLE
Feature/capitalization and tags

### PR DESCRIPTION
**Pull request by ljpengelen**
Addresses https://github.com/borkdude/quickblog/issues/62.

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] I have updated the [CHANGELOG.md](https://github.com/babashka/babashka/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by borkdude** [comment]
Thanks!

**Comment by borkdude** [comment]
@ljpengelen I took a look at your blog (blog.cofx.nl) and I like some of the CSS you have there and also the "Continue reading" feature. If your blog open source? I might want to have those changes in quickblog as well, if you're open to that.

**Comment by borkdude** [comment]
Oh I see `"Continue reading"` is already supported by:

```
`<!-- end-of-preview -->
```

Thanks :)

**Comment by ljpengelen** [comment]
@borkdude, yes, my blog is open source: https://github.com/cofx22/blog. But you're right, everyting you see on blog.cofx.nl is powered by the current version of quickblog. My configuration points to a local version, but that is 100% the same as your version at the moment.

**Comment by borkdude** [comment]
Thanks! If you have anything you want to change to the defaults that would make things look better by default, I'm open to some style changes.

**Pull request merged**
